### ISSUE TITLE
[Enhancement]: Sparrow Texture Atlases

### ISSUE THREAD

**Issue by thepercentageguy** [ceramic-engine/ceramic#100]
It'd be pretty cool if Sparrow Texture Atlases (png spritesheet + xml combo) were supported right out of the box.

**Comment by jeremyfa** [comment]
Loading sparrow/xml texture atlases is actually supported since very recently:

Your atlas file must have `.atlas` extension.

Load your atlas asset in some scene
```haxe
assets.add(Atlases.YOUR_ATLAS);
```

After load, get the atlas and assign a region to a quad
```haxe
var atlas = assets.atlas(Atlases.YOUR_ATLAS);
someQuad.tile = atlas.region('someRegion');
```
