### ISSUE TITLE
``haxelib run ceramic setup`` command should create /usr/local/bin and check permission on macOS

### ISSUE THREAD

**Issue by logo4poop** [ceramic-engine/ceramic#103]
On a fresh install of macOS, ``/usr/local/bin`` does not exist and must be created before. Additionally, to put anything in the ``/usr/local/bin`` requires root access, so it would also be ideal to check for permission before downloading ``ceramic.zip``.

**Comment by jeremyfa** [comment]
This is now fixed in the latest haxelib release, which will use `sudo` (and make the terminal ask for admin password) in order to write into `/usr/local/bin`
