### ISSUE TITLE
Optimization size for web game size in ceramic game engine

### ISSUE THREAD

**Issue by CodeLazier** [ceramic-engine/ceramic#127]
I am currently looking for a game engine that can generate as small web games as possible. I tried using Ceramic, and the default empty project generates a web page of around 1.8MB. Is there a way to further optimize or trim unnecessary features from the project to reduce the final published result?

**Comment by jeremyfa** [comment]
Hi, yes, you can reduce the js file size by using ceramic_web_minify command, which will minify the output js as an additional build step.

Fair to also note that js data will be gzipped by any regular server before being sent via http so the actual size you might actually make users download is generally that gzipped size, and gzip works generally well on js plain text :)

**Comment by CodeLazier** [comment]
Thank you for your message.I will use ceramic to try creating the next game.
