### ISSUE TITLE
Faulty Tiling

### ISSUE THREAD

**Issue by utaner** [ceramic-engine/ceramic#134]
I tried to create a tilemap by examining 'Example Pixel Platformer,' but the map doesn't appear correctly in the game.

**Tiled Editor**
![image](https://github.com/ceramic-engine/ceramic/assets/24855850/26b76a1d-2ec7-4b36-800b-9b3d21e2935e)

**Ceramic**
![image](https://github.com/ceramic-engine/ceramic/assets/24855850/aec198e3-5da3-4f9c-b8c3-b572edb4392b)

**To Reproduce**
1. Download and extract [game.zip](https://github.com/ceramic-engine/ceramic/files/14453963/game.zip)
2. Build project with `ceramic clay run web --setup --assets`
3. See error

**Comment by jeremyfa** [comment]
Fixed the gap with https://github.com/ceramic-engine/ceramic/commit/98c2916cc5dd86219b468ce5a3ad396f3d8ae1d2, but the wrong selected tiles doesn't come from a Ceramic bug. It's the tileset file that is invalid. It states there are 60 columns where there should only be 57. Opened the tsx file with Tiled and saved it again and the errors was corrected.
