### ISSUE TITLE
```haxelib run ceramic setup``` gives an error

### ISSUE THREAD

**Issue by ArdisanZX** [ceramic-engine/ceramic#138]
Reinstalling also hasn't been working.

EDIT: @9Morello 's  pull request fixed my issue.
https://github.com/ceramic-engine/ceramic-haxelib/pull/1

```C:\Users\Person>haxelib run ceramic setup
com/akifox/asynchttp/AsyncHttp.hx:195: 51QrSXxv ERROR:Transfer failed -> Eof
Called from ? line 1
Called from Main.hx line 118
Called from Main.hx line 126
Called from Main.hx line 233
Called from Main.hx line 333
Called from com/akifox/asynchttp/HttpRequest.hx line 136
Called from com/akifox/asynchttp/AsyncHttp.hx line 231
Called from com/akifox/asynchttp/AsyncHttp.hx line 586
Called from Main.hx line 328
Uncaught exception - Http error: 0 / Transfer failed -> Eof

**Comment by jeremyfa** [comment]
There is a PR for this: https://github.com/ceramic-engine/ceramic-haxelib/pull/1 bit it will have to wait next week before being merged.

Meanwhile, yes, you can install Ceramic just by downloading the ceramic-*.zip file for your platform, unzip it where you want (like your home dir) and run ./ceramic link from the tools directory

**Comment by jeremyfa** [comment]
This should be solved now
