### ISSUE TITLE
`Text` changes to allow for a `Password` component

### ISSUE THREAD

**Issue by Jarrio** [ceramic-engine/ceramic#140]
```hx
text = new Text();
text.resolveGlyph = (c:Int, pos:Int) -> {
    return '*'.code;
};
text.content = "blah";
// displays ****
```
> The only change needed to support that would be to let the Text class call the provided resolveGlyph() method for each chararacter, if provided. If the method is not provided, default (current) behaviour still happen

**Comment by jeremyfa** [comment]
Added `text.glyphCode = (charCode:Int, pos:Int) -> ... ;`
