### ISSUE TITLE
[tools] Improve haxe library loading: ensure ceramic projects are self contained

### ISSUE THREAD

**Issue by jeremyfa** [ceramic-engine/ceramic#23]
Currently, generated hxml is using `-lib libname` all over to plug dependencies.

This makes the workflow much more complex than it should and more prone to errors because it makes the hxml file dependent on the host machine configuration and on `haxelib` binary at multiple stages of the build, which may even in some situation get inconsistent (like, libA detected at competion time on IDE X, but unresolved at build time because the haxelib repository is different...)

It will make the builds more predictable if `ceramic` automatically replaces `-lib libName` with `-cp /path/to/libName` (and optional `extraParams.hxml`) in hxml. That would mean `ceramic` tools resolve in advance which lib to use and that this resolution is consistent across every build stage instead of asking the host machine's `haxelib` to do so.

This solution would still allow to use libs from haxelib repository, but ceramic would take care of downloading and installing them locally and provide the correct hxml code to include them.

We could actually make `ceramic` use `haxelib newrepo` to download and store haxe libraries locally and completely isolate haxe dependencies on a per-project basis.

**Comment by samuelbouchet** [comment]
In case it helps: you can use `-lib <name>:version` to specify a version number or even to a git branch using `-lib <name>:git:<gitURL>#branchOrTagOrCommit`. Then configure the project using `haxelib install build.hxml`.

**Comment by jeremyfa** [comment]
Pointing to an exact library version is not the issue here (it can already be done from the project config file, which will be converted to the hxml syntax you mentioned above).

The issue is the dependency with haxelib binary to resolve libraries. It prevents a project to be safely self contained and independant to the local machin config. Ultimately, a ceramic project should work without installing any haxe or haxelib binary globally.

That is why projects like [haxeshim](https://github.com/lix-pm/haxeshim) or [lix](https://github.com/lix-pm/lix.client) exist.

For instance, currently, even if a ceramic project uses a dedidated haxelib binary + repository, the haxe plugin for VSCode will still look for the globally installed haxelib binary (and lib repository), because [it is not possible to specify a haxelib binary properly at the moment](https://github.com/vshaxe/vshaxe/issues/227). There could be similar issues when using other IDEs or other haxe-based tools as well.

``haxelib newrepo`` has also its load of issues [like this one](https://github.com/HaxeFoundation/haxelib/issues/292) making it close to unusable at the moment.

The only reliable way to have 100% predictable dependencies that don't depend on the local machine configuration is **not to use haxelib at all**. That is, using ``-cp`` and pointing to explicit directories, regardless of these being installed with git, haxelib or whatever tool you use...

**Comment by jeremyfa** [comment]
Now that this is solved, https://github.com/HaxeFoundation/haxelib/issues/292, it is actually possible to have self contained projects with plain haxe + haxelib. That is probably the route that will be adopted by ceramic projects: a project has its own `.haxelib` repository that won't collide with any other haxelib repository. It would be even better if ceramic itself could be integrated as a haxe library as well

**Comment by jeremyfa** [comment]
This is now solved. Ceramic projects now use a local `.haxelib` repository that won't collide with system-wide configuration
