### ISSUE TITLE
[plugins] Ceramic not detecting Unity

### ISSUE THREAD

**Issue by polybiusproxy** [ceramic-engine/ceramic#62]
# Unity is not being detected by Ceramic
Hi there,
![image](https://user-images.githubusercontent.com/47796739/122448134-bac52300-cfa4-11eb-80f5-a4e35fc5cdd6.png)

So this error appeared, when I already have Unity installed through Unity Hub, and as the wiki says, its 2020.LTS.

## Location where Unity gets installed (default for me):
![image](https://user-images.githubusercontent.com/47796739/122448306-ea742b00-cfa4-11eb-91b3-cbd31542c10d.png)
### Screenshot of Unity:
![image](https://user-images.githubusercontent.com/47796739/122448744-62425580-cfa5-11eb-87aa-4b6bcc06cbc6.png)

I can't build, and I don't know what is the problem...

**Comment by jeremyfa** [comment]
Ceramic is looking at default install path of Unity Hub, which is: `C:/Program Files/Unity/Hub/Editor/`).

It seems your path is different and that's probably why ceramic doesn't find it.

You can however specify in your ceramic project an explicit Unity path in that case (edit your project's ceramic.yml):

```yaml
app:

    unity:
        path: 'C:/Path/to/your/unity/editor'
```

**Comment by polybiusproxy** [comment]
> Ceramic is looking at default install path of Unity Hub, which is: `C:/Program Files/Unity/Hub/Editor/`).
> 
> It seems your path is different and that's probably why ceramic doesn't find it.
> 
> You can however specify in your ceramic project an explicit Unity path in that case (edit your project's ceramic.yml):
> 
> ```yaml
> app:
> 
>     unity:
>         path: 'C:/Path/to/your/unity/editor'
> ```

thanks, it worked!
