### ISSUE TITLE
Language server failing because of `WindowData::DEFAULT_HEIGHT`

### ISSUE THREAD

**Issue by alberteddu** [ceramic-engine/ceramic#74]
> Haxe: 4.0.0-rc.5+4a745347f
> Ceramic: v0.8.5

When coding using VS Code (I followed the Wiki in order to set it up), the language server fails with the error:

> Failed - try fixing the error(s) and restarting the language server:
>
> [...[/ceramic/plugins/elements/runtime/src/elements/WindowData.hx:13: characters 2-68 : Inline variable initialization must be a constant value
> [...]/ceramic/plugins/elements/runtime/src/elements/Im.hx:171: characters 101-126 : Parameter default value should be constant

I think the problem is here:

```public inline static final DEFAULT_HEIGHT:Float = ViewSize.auto();```

Using `ViewSize.auto()` as opposed to just the value `-60001.0`, (the language server works when setting the constant) but I'm not really experience with Haxe so I'm not sure. There's probably a better way.

I could put together a pull request if needed and if I understand the solution :)

**Comment by jeremyfa** [comment]
Should be fixed by now.
