### ISSUE TITLE
Unable to generate android apk file

### ISSUE THREAD

**Issue by ccpplinux** [ceramic-engine/ceramic#75]
When I am trying to generate android apk file for my hello_world project using the command "ceramic android export apk" then I am getting following error message:

Error: Could not detect Android API platforms in "/home/ccpplinux/Android/Sdk/ndk/android-ndk-r23b/ndk-which/platforms"
Compile C++ for arch armv7
Error: Could not detect Android API platforms in "/home/ccpplinux/Android/Sdk/ndk/android-ndk-r23b/ndk-which/platforms"
Failed to compile C++ for arch armv7

> Task :app:haxeBuildRelease FAILED
> Task :app:processReleaseManifestForPackage

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:haxeBuildRelease'.
> Process 'command './build-haxe.sh'' finished with non-zero exit value 1

* Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':app:haxeBuildRelease'.

I have downloaded latest NDK LTS but it is not working. Can you please help me what is going wrong?

**Comment by jeremyfa** [comment]
This is because HXCPP can't find your NDK. You can edit `.hxcpp-config.xml` in your home directory to add android SDK/NDK config:

```xml
      <set name="ANDROID_SETUP" value="true" />
      <set name="ANDROID_SDK" value="/Path/to/your/Android/sdk" />
      <set name="ANDROID_NDK_ROOT" value="/Path/to/your/Android/NDK" />
      <set name="ANDROID_NDK_DIR" value="/Path/to/your/Android/NDK" />
```
