### ISSUE TITLE
Pausing Nape

### ISSUE THREAD

**Issue by qeshi** [ceramic-engine/ceramic#76]
Hi!

I implemented pausing in my physics game by setting the scene's `paused` field to `true`. But Nape doesn't get paused so the physics simulation is still running.

So I implemented a quick and dirty way to pause all Nape spaces since I'm only using one space.

Like this:

```
@:allow(ceramic.App)
class NapeSystem extends System {

    public var paused:Bool = false;
    
    ....     
    
    inline function updateSpace(space:nape.space.Space, delta:Float):Void {

        if (!this.paused) {
            space.step(delta);
        }       

    }
```

I don't know what the correct way to implement pause for specific spaces though.

I can't extend the Nape.Space class since it is final. Do you have any ideas what would be a good solution?

**Comment by jeremyfa** [comment]
Hi,

I believe pausing the nape system in order not to update spaces is a good option.

I'll keep that issue open and come up with a way to pause nape when I have the time to take a look!
