### ISSUE TITLE
Excuse me, if I want to make 2d mobile games, is ceramic friendly to beginners?

### ISSUE THREAD

**Issue by toutiewa** [ceramic-engine/ceramic#81]
Excuse me, if I want to make 2d mobile games, is ceramic friendly to beginners?

I have no basic knowledge of C++ language.

**Comment by jeremyfa** [comment]
Hi, you don't really need to know C++ to use ceramic, but you need to be familiar with programming in general (including some basics of Haxe at least), using a terminal etc.... If you are completely new to programming, I wouldn't recommend you to use Ceramic.
