### ISSUE TITLE
how to generate android apk file?

### ISSUE THREAD

**Issue by toutiewa** [ceramic-engine/ceramic#82]
how to generate android apk file?

When I execute "Build Android" in vscode, the apk is not generated.

**Comment by jeremyfa** [comment]
When you select build android and then press CTRL/CMD + Shift + B, it exports an Android Studio project. You then export the apk from Android Studio directly.

**Comment by toutiewa** [comment]
> When you select build android and then press CTRL/CMD + Shift + B, it exports an Android Studio project. You then export the apk from Android Studio directly.

Can you be more specific?

**Comment by jeremyfa** [comment]
Ceramic exports an android studio project (in `project/android` directory), so you need to open that project with Android studio and export your APK from there (using Build > Generate signed Bundle / APK...). If you want to export an Android app you'll need basic knowledge on how to use Android Studio to build, export etc... which is outside of the scope of ceramic itself.
