### ISSUE TITLE
Link is dead

### ISSUE THREAD

**Issue by qeshi** [ceramic-engine/ceramic#92]
https://github.com/ceramic-engine/ceramic/blob/bf5cc0010d2db5cb19447df0da15174f45333ab6/README.md?plain=1#L15

Hi this link is dead.
I think it should be this one

https://ceramic-engine.com/guides/discover-ceramic/

**Comment by jeremyfa** [comment]
Indeed, I changed the paths recently, will fix that, thanks for reporting!
